import numpy as np

# DEBUG Settings
DEBUG_MODE = 1

# Game Constants
MAP_STRING = "src\\game\\levels\\testlevel3.txt"
PLAYER_VELOCITY = 1 # 0.2
SCREEN_WIDTH = 500
SCREEN_HEIGHT = 500
SCREEN_SIZE = 20
PLAYER_WIDTH = 25
PLAYER_HEIGHT = 25

# Agent Constants
AGENT_CNT = 32 # 32
TRIAL_TIME = 60*2
TRIAL_INCREASE_TIME = 30
TRIAL_INCREASE_RATE = 10
AGENT_VISION_RADIUS = 3
AGENT_NN_NUM_INPUTS = (AGENT_VISION_RADIUS*2+1)**2
AGENT_NN_NUM_OUTPUTS = 4
AGENT_NN_DIMENSIONS = np.array([AGENT_NN_NUM_INPUTS, 50, 100, 25, 15, AGENT_NN_NUM_OUTPUTS])
AGENT_NN_CHANGE_RATE = 10